plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: bin/@yarnpkg/plugin-angular.js
    spec: '@yarnpkg/plugin-angular'

yarnPath: .yarn/releases/yarn-2.4.2.cjs
